// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test_case1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test_case1', async function() {
    await driver.get("http://selenium_tests/")
    await driver.manage().window().setRect(973, 693)
    await driver.findElement(By.linkText("login.php")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("test")
    await driver.findElement(By.css("form")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("pwcorrect")
    await driver.findElement(By.css("form")).click()
    await driver.findElement(By.css("tr:nth-child(3) input")).click()
    await driver.findElement(By.css("html")).click()
  })
})
