language:
  node_js
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
before_install:
  - npm install --save-dev codecov
  - npm install --save-dev mocha
  - npm install --save-dev nyc
  - npm install --save npm-git-install
script:
  - npm run test
  - npm run report-coverage
