language:
  node_js
before_install:
  - npm install -g codecov
  - npm install --save-dev mocha
  - npm install --save-dev nyc
  - make test
script:
  - npm test
  - npm run test
  - npm run report-coverage
