language:
  node_js
before_install:
  - npm install -g codecov
  - npm install --save-dev mocha
  - npm install --save-dev nyc
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - ./node_modules/.bin/codecov
  - codecov
