language: node_js
node_js:
  - 15
script: 
  - npm install codecov nyc --save-dev
  - npm install mocha-lcov-reporter --save-dev
  - npm install

after_sucess:  
  - npm run test && bash <(curl -s https://codecov.io/bash) -v
