language:
  node_js
before_install:
  - npm install -g codecov
  - npm i -D nyc
  - cd istanbul-mocha && npm install && cd ..
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
