language:
  node_js
before_install:
  - npm install -g codecov
  - npm install --save-dev mocha
  - npm install --save-dev nyc
script:
  - nyc npm test
  - nyc report --reporter=text-lcov > coverage.lcov
  - ./node_modules/.bin/codecov
  - codecov
